project:
  type: website
  output-dir: docs

website:
  title: Project CCHAIN
  favicon: site/assets/icon.png
  open-graph: true
  twitter-card: true
  navbar:
    title: false
    background: "#ec4646"
    search: true
    left:
      - text: "Home"
        file: site/index.qmd
      - text: "About"
        file: site/about.qmd
      - text: "Open data"
        file: site/open_data.qmd
      - text: "Open code"
        file: site/open_code.qmd
      - text: "Open model"
        file: site/open_model.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
format:
  html: 
    toc: true
    theme: united
    fontsize: 1.1em
    linestretch: 1.7 