project:
  type: website
  output-dir: docs

notebook-links: false

website:
  title: Project CCHAIN
  favicon: assets/icon.png
  open-graph: true
  twitter-card: true
  navbar:
    title: false
    background: "#ec4646"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "About"
        file: about.qmd
      - text: "Open data"
        file: open_data.qmd
      - text: "Open viz"
        file: open_viz.qmd
      - text: "Open model"
        href: open_model.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/thinkingmachines/project-cchain/
          - text: Report a Bug
            url:  https://github.com/thinkingmachines/project-cchain/issues/
format:
  html: 
    toc: true
    theme: united
    fontsize: 1.1em
    linestretch: 1.7 